Resources:
  serviceUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: service-user-pool-${opt:stage, self:provider.stage}
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
  serviceUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: service-user-pool-client-${opt:stage, self:provider.stage}
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      UserPoolId:
        Ref: serviceUserPool
      CallbackURLs: 
        - ${self:provider.environment.CALLBACK_URL}
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      SupportedIdentityProviders: 
        - COGNITO
  serviceUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain 
    Properties:
      UserPoolId: 
        Ref: serviceUserPool
      Domain: service-user-pool-domain-${opt:stage, self:provider.stage}-${self:provider.environment.DOMAIN_SUFFIX}
